### PR TITLE
Add contributing info

### PR DESCRIPTION
**Pull request by rtapella**

### CODE REVIEW

**Review by wphyojpl — APPROVED** [review]
There are jpl artifactory urls in it. 
I guess we can't avoid it, but keep in mind to update them once OCS is open sourced.

**Comment by rtapella** [comment]
> There are jpl artifactory urls in it. I guess we can't avoid it, but keep in mind to update them once OCS is open sourced.

true. OCS open-source is in progress so we can update it at that time

**Comment by rtapella** [comment]
placeholder url for OCS client: https://github.com/NASA-AMMOS/ocs-js-client

**Comment by rtapella** [comment]
contributing md file also has some broken links that we/I should fix

**Pull request merged**
